import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  UserOutline,
  LogoutOutline,
  DownOutline,
  EyeOutline,
  EyeInvisibleOutline,
  CheckOutline,
  MailOutline,
  SafetyCertificateOutline,
  CheckCircleFill,
  CloseCircleFill,
  TeamOutline,
  ShoppingCartOutline,
  SettingOutline,
  FileSearchOutline,
  DollarOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  UserOutline,
  LogoutOutline,
  DownOutline,
  EyeOutline,
  EyeInvisibleOutline,
  CheckOutline,
  MailOutline,
  SafetyCertificateOutline,
  CheckCircleFill,
  CloseCircleFill,
  TeamOutline,
  ShoppingCartOutline,
  SettingOutline,
  FileSearchOutline,
  DollarOutline,
];
